zkConfig :
  connectionString: "localhost:2181"
  readOnly:  "true"

k8sConfig:
  namespace: "yak-core-preprod"
  kubeApiHost: "10.24.7.90"
  kubeApiPort: "6443"
  kubeConfigEnvironmentValue: "/etc/hbase-compactor/secret-token"
  readTimeout: 50000
  additionalLabels:
    hbase-compactor/app-id: "preprod-yak-core"
    hbase-compactor/version: "v1"
  additionalAnnotations:
    meta.helm.sh/release-name: "yak-hbase-compactor"

hadoopUserName: "yak"

store: k8

logging:
  level: INFO
  appenders:
    - type: console
      threshold: INFO
      timeZone: IST
      logFormat: "%-5level [%date] [%thread] [%X{contextId}] [%X{userId}] [%cyan(%logger{0})]: %message%n"

server:
  rootPath: /api
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8083
  requestLog:
    appenders:
      - type: console
        threshold: INFO
        timeZone: IST
        logFormat: "%-5level [%date] [%thread] [%X{contextId}] [%X{userId}] [%cyan(%logger{0})]: %message%n"