namespace: yak-compaction-preprod
fcp:
  team: "yak"
  appId: "preprod-yak-compaction"
  mail: "yak-dev"
  service: "fk-hbase-compactor-api"

mtl:
  cosmos:
    statsd: disabled
    tail: disabled
    config: cosmos
  asterix: disabled

pod:
  replicaCount: 1

hostpopulator:
  state: disabled

services:
  - name: preprod-yak-compactor
    type: LoadBalancer
    selector:
      app: yak-ui
    ports:
      - port: 8082
        targetPort: 8082
        protocol: TCP
        name: http
    LoadBalancer:
      vip: preprod-yak-compactor-vip-1
      backendService: preprod-yak-compactor-vip-1
      frontendPort: 80
      backendPort: 8082
      healthCheckPort: 8083
      healthCheckPath: /healthcheck
      healthCheckTimeout: 1000ms
      healthCheckInterval: 5s
      loadBalancingAlgorithm: leastconn
      doNotDeleteVip: "true"
      mode: "http"

image:
  yak-compactork:
    registry: jfrog.fkinternal.com
    repository: yak-compactor/fk-hbase-compactor-api
    volumes:
      - app
    livenessCheck:
      initialDelay: 180
      checkInterval: 15
      method: tcp
      port: 9311
    ports:
      - name: http
        containerPort: 9311
    maxCpuLimit: 1
    maxCpuAsk: 1
    maxMemoryLimit: 2Gi
    maxMemoryAsk: 2Gi

volumes:
  - name: app
    type: configMap
    value: app-config
    mountPath: /etc/hbase-compactor/

configMaps:
  envName: preprod
  configs:
    - name: app-config
      source: dir
      sourceLoc: compactor
    - name: cosmos
      source: dir
      sourceLoc: cosmos
    - name: host-populator-config
      source: dir
      sourceLoc: host-populator

annotations:
  sidecar.istio.io/inject: "false"

newrelic:
  state: disabled