zkConfig :
  connectionString: "localhost:2181"
  readOnly:  "true"

k8sConfig:
  namespace: "xxxx"
  readTimeout: 50000
  additionalLabels:
    hbase-compactor/app-id: "xxxx"
    hbase-compactor/version: "v1"
  additionalAnnotations:
    meta.helm.sh/release-name: "xxxx"

hadoopUserName: "xxxx"

store: k8

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ${logger.console.level}
      timeZone: IST
      logFormat: "%-5level [%date] [%thread] [%X{contextId}] [%X{userId}] [%cyan(%logger{0})]: %message%n"

server:
  rootPath: /api
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8083
  requestLog:
    appenders:
      - type: file
        currentLogFilename: access.log
        archivedLogFilenamePattern: access-%i.log
        logFormat: '%h [%date{dd MMM yyyy;HH:mm:ss.SSS}] - "%r" %s %b %D'
        archive: true
        archivedFileCount: 1
        timeZone: IST
        maxFileSize: 200MB
        neverBlock: true