namespace: yak-core-playground
fcp:
  team: "yak"
  appId: "playground-yak-core"
  mail: "yak-dev"
  service: "fk-hbase-compactor"

mtl:
  cosmos:
    statsd: disabled
    tail: disabled
    config: cosmos
  asterix: disabled

pod:
  replicaCount: 1

hostpopulator:
  state: enabled

image:
  yak-compactor:
    registry: jfrog.fkinternal.com
    repository: yak-compactor/fk-hbase-compactor
    volumes:
      - app
    livenessCheck:
      initialDelay: 180
      checkInterval: 15
      method: tcp
      port: 9311
    ports:
      - name: http
        containerPort: 9311
    maxCpuLimit: 1
    maxCpuAsk: 1
    maxMemoryLimit: 2Gi
    maxMemoryAsk: 2Gi

volumes:
  - name: app
    type: configMap
    value: app-config
    mountPath: /etc/hbase-compactor/


annotations:
  sidecar.istio.io/inject: "false"

newrelic:
  state: disabled