namespace: yak-core-playground
fcp:
  team: "yak"
  appId: "playground-yak-core"
  mail: "yak-dev"
  service: "fk-hbase-compactor"

mtl:
  cosmos:
    statsd: disabled
    tail: disabled
    config: cosmos
  asterix: disabled

pod:
  replicaCount: 1

hostpopulator:
  state: enabled

image:
  yak-compactor:
    registry: jfrog.fkinternal.com
    repository: yak-compactor/fk-hbase-compactor
    command: [ "/entrypoint" ]
    args: [ "com.flipkart.yak.HCompactor"]
    volumes:
      - app
    livenessCheck:
      initialDelay: 180
      checkInterval: 15
      method: tcp
      port: 9311
    ports:
      - name: http
        containerPort: 9311
    maxCpuLimit: 1
    maxCpuAsk: 1
    maxMemoryLimit: 2Gi
    maxMemoryAsk: 2Gi
    envVarsFrom:
      - from: secret
        name: hadoop-user

volumes:
  - name: app
    type: configMap
    value: app-config
    mountPath: /etc/hbase-compactor/


annotations:
  sidecar.istio.io/inject: "false"

newrelic:
  state: disabled

serviceAccount:
  name: yak-compactor-config-reader
  role: Role
  permissions:
    - apiGroup: ""
      resource: configmaps
      actions:
        - "get"
        - "list"
        - "watch"